name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true
# account_id = "your-account-id"

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail-db"
database_id = "your-d1-database-id"

[[kv_namespaces]]
binding = "kv"
id = "your-kv-namespace-id"

[[r2_buckets]]
binding = "r2"
bucket_name = "cloud-mail-r2"

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[[send_email]]
name = "EMAIL"
remote = true

[[routes]]
pattern = "mail.example.com/*"
zone_id = "your-zone-id"

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行

[vars]
orm_log = false
domain = ["mail.example.com"]
admin = "admin@mail.example.com"
jwt_secret = "your-random-jwt-secret-string"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
